### ISSUE TITLE
Can't use global chat 1.14

### ISSUE THREAD

**Issue by AttyZ** [ryandw11/UltraChat#2] opened 2019-07-05 12:16 UTC
I'm just going to post the error log

I'm runnin the 1.14.3 revision of spigot.  Ive got placeholderAPI. I did not download essentialsx like recommended. I have Vault and Lucky permission

Vault rev v1.7.2-b107
PlaceholderAPI rev v2.10.3
LuckPerms rev v4.4.1
Edit: I also just ensured I had the latest java, jre1.8.0_211. This is not the cause of the issue.

As a coder, at a glance, I think 'Multiverse core' could be causing a conflict here with there being various dimensions someone can be in at once. But it could just be that I've configured your mod improperly or am using a very poor permissions system.

Anything I can do to help you track down this error, I'll try. I'm going to be watching this.

`org.bukkit.command.CommandException: Unhandled exception executing command 'global' in plugin UltraChat v2.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:709) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.IllegalStateException: GlobalChatEvent cannot be triggered asynchronously from primary server thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:497) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	at me.ryandw11.ultrachat.commands.Global.onCommand(Global.java:48) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.3.jar:git-Spigot-935adb3-bf32933]
	... 17 more
[07:37:39] [Server thread/INFO]: OrchidQuill issued server command: /global "boi"`

**Comment by ryandw11** [comment] 2019-07-05 19:58
I think I know what the problem is. I will look at the code and fix it.

On a further note:
Luckperms is a great permission plugin and I use it all the time.
Essentialsx is not recommended, it is just that the plugin works with it.

**Comment by AttyZ** [comment] 2019-07-08 06:26
Forgive me for being useless, but I have no idea how to compile this for testing. I tried to install gradle but I've never had to do this before. I will just have to wait for you to upload this fix as .jar to the spigot site, and will report if this fixed the problem

**Comment by ryandw11** [comment] 2019-07-08 13:27
Oh sorry about that. I am actually going to pair the bug fix with a major plugin update. I wasn't expecting you to compile it. I posted an update on Spigot right now. The bug is fixed from my testing so I will close this report now. If it is not fix feel free to comment here again and I'll reopen this report.

**Closed by ryandw11** 2019-07-08 13:27 UTC
Labels: bug
